// PdfToImageService v3.0.145
import 'dart:typed_data';
//
// Convert PDF bytes → PNG-embedded PDF.
// Workflow: PDF(form with fonts) → render to raster PNG → embed as PNG image in new PDF → push to EMR
// The resulting PDF contains ONLY an image → no text/font rendering on EMR server → Vietnamese displays correctly
//
// Uses `printing` package's Printing.raster() API (already in pubspec) - no extra packages needed.

import 'package:flutter/foundation.dart' show debugPrint;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfToImageService {
  /// Convert PDF to a PDF that contains the rendered form as a PNG image.
  /// No text elements - only embedded image → EMR server displays correctly.
  ///
  /// [pdfBytes] - the original PDF bytes (generated by _buildPdf with custom fonts)
  /// [dpi] - resolution (default 150 DPI - good quality + reasonable size)
  ///
  /// Returns PNG-embedded PDF bytes, or null if conversion fails.
  static Future<Uint8List?> pdfToPngPdf(
    Uint8List pdfBytes, {
    int dpi = 150,
  }) async {
    try {
      // Step 1: Render ALL PDF pages to PNG (v3.0.156 - fix multi-page bug)
      final pages = <Uint8List>[];

      await for (final raster in Printing.raster(pdfBytes, dpi: dpi.toDouble())) {
        final pngBytes = await raster.toPng();
        pages.add(pngBytes);
        // v3.0.156: Removed `break;` - was causing only first page to be captured
      }

      if (pages.isEmpty) {
        debugPrint('[PdfToImage] No pages rendered from PDF');
        return null;
      }

      debugPrint('[PdfToImage] PDF → ${pages.length} PNG pages @ $dpi DPI');

      // Step 2: Build new PDF containing ALL PNG pages
      // Get page dimensions - use A4 default (595 x 842 points) scaled to DPI
      const pageWidthPt = 595.0;
      const pageHeightPt = 842.0;
      final scale = dpi / 72.0;
      final pageFormat = PdfPageFormat(pageWidthPt * scale, pageHeightPt * scale);

      final doc = pw.Document();
      for (final pngBytes in pages) {
        doc.addPage(
          pw.Page(
            pageFormat: pageFormat,
            margin: pw.EdgeInsets.zero,
            build: (ctx) {
              return pw.Image(
                pw.MemoryImage(pngBytes),
                fit: pw.BoxFit.contain,
                width: pageWidthPt * scale,
                height: pageHeightPt * scale,
              );
            },
          ),
        );
      }

      final outputPdf = await doc.save();
      debugPrint('[PdfToImage] PNG-in-PDF created: ${outputPdf.length} bytes, ${pages.length} pages');
      return outputPdf;
    } catch (e, st) {
      debugPrint('[PdfToImage] Error: $e\n$st');
      return null;
    }
  }
}
