// PdfToImageService v3.0.145
//
// Convert PDF bytes → PNG-embedded PDF.
// Workflow: PDF(form with fonts) → render to RGBA pixels → embed as PNG image in new PDF → push to EMR
// The resulting PDF contains ONLY an image → no text/font rendering on EMR server → Vietnamese displays correctly
//
// Uses Android native PdfRenderer via platform channel (no external packages needed).
// Uses `image` package (already in pubspec) for PNG encoding.

import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:image/image.dart' as img;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfToImageService {
  static const _channel = MethodChannel('his_mobile/pdf_renderer');

  /// Convert PDF to a PDF that contains the rendered form as a PNG image.
  /// No text elements - only embedded image → EMR server displays correctly.
  ///
  /// [pdfBytes] - the original PDF bytes (generated by _buildPdf with custom fonts)
  /// [dpi] - resolution (default 150 DPI - good quality + reasonable size)
  ///
  /// Returns PNG-embedded PDF bytes, or null if conversion fails.
  static Future<Uint8List?> pdfToPngPdf(
    Uint8List pdfBytes, {
    int dpi = 150,
  }) async {
    try {
      // Step 1: Render PDF page to PNG using Android native PdfRenderer
      final pngBytes = await _channel.invokeMethod<Uint8List>('renderPdfPageToPng', {
        'pdfBytes': pdfBytes,
        'dpi': dpi,
        'pageIndex': 0,
      });

      if (pngBytes == null) {
        return null;
      }

      // Step 2: Get page dimensions from PDF for proper page sizing
      // Use default A4 dimensions (595 x 842 points) - close enough for most medical forms
      const pageWidthPt = 595.0;
      const pageHeightPt = 842.0;
      final scale = dpi / 72.0;
      final pageFormat = PdfPageFormat(pageWidthPt * scale, pageHeightPt * scale);

      // Step 3: Build new PDF containing only the PNG image
      final doc = pw.Document();
      doc.addPage(
        pw.Page(
          pageFormat: pageFormat,
          margin: pw.EdgeInsets.zero,
          build: (ctx) {
            return pw.Image(
              pw.MemoryImage(pngBytes),
              fit: pw.BoxFit.contain,
              width: pageWidthPt * scale,
              height: pageHeightPt * scale,
            );
          },
        ),
      );

      final outputPdf = await doc.save();
      return outputPdf;
    } catch (e, st) {
      return null;
    }
  }
}
